/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as protectedIndexRouteImport } from './routes/(protected)/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as authSignupIndexRouteImport } from './routes/(auth)/signup/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password/index'
import { Route as protectedWorkspacePagesRouteRouteImport } from './routes/(protected)/$workspace/pages/route'
import { Route as protectedWorkspaceLinksRouteRouteImport } from './routes/(protected)/$workspace/links/route'
import { Route as protectedWorkspaceLinksIndexRouteImport } from './routes/(protected)/$workspace/links/index'
import { Route as ApiAuthWebSplatRouteImport } from './routes/api/auth/web/$'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedWorkspacePagesRouteRoute =
  protectedWorkspacePagesRouteRouteImport.update({
    id: '/$workspace/pages',
    path: '/$workspace/pages',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedWorkspaceLinksRouteRoute =
  protectedWorkspaceLinksRouteRouteImport.update({
    id: '/$workspace/links',
    path: '/$workspace/links',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedWorkspaceLinksIndexRoute =
  protectedWorkspaceLinksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedWorkspaceLinksRouteRoute,
  } as any)
const ApiAuthWebSplatRoute = ApiAuthWebSplatRouteImport.update({
  id: '/api/auth/web/$',
  path: '/api/auth/web/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/health': typeof ApiHealthRoute
  '/': typeof protectedIndexRoute
  '/$workspace/links': typeof protectedWorkspaceLinksRouteRouteWithChildren
  '/$workspace/pages': typeof protectedWorkspacePagesRouteRoute
  '/forgot-password/': typeof authForgotPasswordIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/signup/': typeof authSignupIndexRoute
  '/api/auth/web/$': typeof ApiAuthWebSplatRoute
  '/$workspace/links/': typeof protectedWorkspaceLinksIndexRoute
}
export interface FileRoutesByTo {
  '/api/health': typeof ApiHealthRoute
  '/': typeof protectedIndexRoute
  '/$workspace/pages': typeof protectedWorkspacePagesRouteRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/api/auth/web/$': typeof ApiAuthWebSplatRoute
  '/$workspace/links': typeof protectedWorkspaceLinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/(protected)/': typeof protectedIndexRoute
  '/(protected)/$workspace/links': typeof protectedWorkspaceLinksRouteRouteWithChildren
  '/(protected)/$workspace/pages': typeof protectedWorkspacePagesRouteRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/api/auth/web/$': typeof ApiAuthWebSplatRoute
  '/(protected)/$workspace/links/': typeof protectedWorkspaceLinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/health'
    | '/'
    | '/$workspace/links'
    | '/$workspace/pages'
    | '/forgot-password/'
    | '/login/'
    | '/signup/'
    | '/api/auth/web/$'
    | '/$workspace/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/health'
    | '/'
    | '/$workspace/pages'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/api/auth/web/$'
    | '/$workspace/links'
  id:
    | '__root__'
    | '/(auth)'
    | '/(protected)'
    | '/api/health'
    | '/(protected)/'
    | '/(protected)/$workspace/links'
    | '/(protected)/$workspace/pages'
    | '/(auth)/forgot-password/'
    | '/(auth)/login/'
    | '/(auth)/signup/'
    | '/api/auth/web/$'
    | '/(protected)/$workspace/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthWebSplatRoute: typeof ApiAuthWebSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/$workspace/pages': {
      id: '/(protected)/$workspace/pages'
      path: '/$workspace/pages'
      fullPath: '/$workspace/pages'
      preLoaderRoute: typeof protectedWorkspacePagesRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/$workspace/links': {
      id: '/(protected)/$workspace/links'
      path: '/$workspace/links'
      fullPath: '/$workspace/links'
      preLoaderRoute: typeof protectedWorkspaceLinksRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/$workspace/links/': {
      id: '/(protected)/$workspace/links/'
      path: '/'
      fullPath: '/$workspace/links/'
      preLoaderRoute: typeof protectedWorkspaceLinksIndexRouteImport
      parentRoute: typeof protectedWorkspaceLinksRouteRoute
    }
    '/api/auth/web/$': {
      id: '/api/auth/web/$'
      path: '/api/auth/web/$'
      fullPath: '/api/auth/web/$'
      preLoaderRoute: typeof ApiAuthWebSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedWorkspaceLinksRouteRouteChildren {
  protectedWorkspaceLinksIndexRoute: typeof protectedWorkspaceLinksIndexRoute
}

const protectedWorkspaceLinksRouteRouteChildren: protectedWorkspaceLinksRouteRouteChildren =
  {
    protectedWorkspaceLinksIndexRoute: protectedWorkspaceLinksIndexRoute,
  }

const protectedWorkspaceLinksRouteRouteWithChildren =
  protectedWorkspaceLinksRouteRoute._addFileChildren(
    protectedWorkspaceLinksRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedIndexRoute: typeof protectedIndexRoute
  protectedWorkspaceLinksRouteRoute: typeof protectedWorkspaceLinksRouteRouteWithChildren
  protectedWorkspacePagesRouteRoute: typeof protectedWorkspacePagesRouteRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedIndexRoute: protectedIndexRoute,
  protectedWorkspaceLinksRouteRoute:
    protectedWorkspaceLinksRouteRouteWithChildren,
  protectedWorkspacePagesRouteRoute: protectedWorkspacePagesRouteRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthWebSplatRoute: ApiAuthWebSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
