/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeyIndexRouteImport } from './routes/$key/index'
import { Route as PasswordKeyRouteImport } from './routes/password/$key'
import { Route as KeySlugRouteImport } from './routes/$key/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyIndexRoute = KeyIndexRouteImport.update({
  id: '/$key/',
  path: '/$key/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordKeyRoute = PasswordKeyRouteImport.update({
  id: '/password/$key',
  path: '/password/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const KeySlugRoute = KeySlugRouteImport.update({
  id: '/$key/$slug',
  path: '/$key/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$key/$slug': typeof KeySlugRoute
  '/password/$key': typeof PasswordKeyRoute
  '/$key/': typeof KeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$key/$slug': typeof KeySlugRoute
  '/password/$key': typeof PasswordKeyRoute
  '/$key': typeof KeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$key/$slug': typeof KeySlugRoute
  '/password/$key': typeof PasswordKeyRoute
  '/$key/': typeof KeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$key/$slug' | '/password/$key' | '/$key/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$key/$slug' | '/password/$key' | '/$key'
  id: '__root__' | '/' | '/$key/$slug' | '/password/$key' | '/$key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeySlugRoute: typeof KeySlugRoute
  PasswordKeyRoute: typeof PasswordKeyRoute
  KeyIndexRoute: typeof KeyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$key/': {
      id: '/$key/'
      path: '/$key'
      fullPath: '/$key/'
      preLoaderRoute: typeof KeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/$key': {
      id: '/password/$key'
      path: '/password/$key'
      fullPath: '/password/$key'
      preLoaderRoute: typeof PasswordKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$key/$slug': {
      id: '/$key/$slug'
      path: '/$key/$slug'
      fullPath: '/$key/$slug'
      preLoaderRoute: typeof KeySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeySlugRoute: KeySlugRoute,
  PasswordKeyRoute: PasswordKeyRoute,
  KeyIndexRoute: KeyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
